export const SERVER_IP = "http://192.168.20.88";

export const categoriesToCheck = [
  "Illicit Drugs",
  "Firearms & Weapons",
  "Sexual",
  "Legal",
];

export const illicitDrugs = [
  "droga",
  "narcótico",
  "estupefaciente",
  "cocaína",
  "cocaina",
  "marihuana",
  "cannabis",
  "heroína",
  "heroina",
  "opio",
  "crack",
  "metanfetamina",
  "LSD",
  "éxtasis",
  "extasis",
  "anfetamina",
  "MDMA",
  "PCP",
  "alucinógeno",
  "alucinogeno",
  "psicodélico",
  "psicodelico",
  "hachís",
  "hierba",
  "porro",
  "pastilla",
  "speed",
  "perico",
  "ácido",
  "acido",
  "basuco",
  "piedra",
  "yerba",
  "cogollo",
  "fumar",
  "inhalar",
  "drogadicción",
  "drogadiccion",
  "adicción",
  "adiccion",
  "traficante",
  "narcotráfico",
  "narcotrafico",
  "distribuidor",
  "dealer",
  "narcotraficante",
  "narco",
  "cartel",
  "contrabando",
  "clandestino",
  "adicto",
  "drogodependiente",
  "consumo",
  "dosis",
  "drogarse",
  "drogando",
  "sobredosis",
  "síndrome de abstinencia",
  "hachis",
];

export const gunsWeapons = [
  "arma",
  "arma de fuego",
  "pistola",
  "revólver",
  "rifle",
  "escopeta",
  "fusil",
  "metralleta",
  "ametralladora",
  "subfusil",
  "munición",
  "municion",
  "bala",
  "cartucho",
  "cargador",
  "gatillo",
  "cañón",
  "cañon",
  "culata",
  "mira",
  "silenciador",
  "corredera",
  "recámara",
  "recamara",
  "fusil de asalto",
  "ak-47",
  "ar-15",
  "uzi",
  "beretta",
  "glock",
  "colt",
  "smith & wesson",
  "browning",
  "winchester",
  "wossberg",
  "heckler & koch",
  "desert eagle",
  "disparan",
  "calibre",
  "balística",
  "balistica",
  "municionar",
  "recargar",
  "disparar",
  "balacera",
  "tiroteo",
  "armamento",
  "militar",
  "policía",
  "policia",
  "delito armado",
  "contrabando de armas",
  "contrabando",
  "tráfico de armas",
  "tráfico",
  "trafico",
  "venta ilegal de armas",
  "posesión ilegal de armas",
  "posesion ilegal de armas",
  "revolver",
  "delito",
];

export const sexual = [
  "sexo",
  "sexualidad",
  "erótico",
  "erótica",
  "erotico",
  "erotica",
  "pene",
  "vagina",
  "tetas",
  "sensualidad",
  "culo",
  "coño",
  "testiculos",
  "testículos",
  "ano",
  "sensuales",
  "sensual",
  "deseo",
  "placer",
  "pasión",
  "pasion",
  "intimidad",
  "lujuria",
  "excitación",
  "excitante",
  "exitacion",
  "orgasmo",
  "orgásmico",
  "orgasmico",
  "estimulación",
  "estimulacion",
  "estimulante",
  "coito",
  "relaciones",
  "sexuales",
  "hacer el amor",
  "follar",
  "actividad sexual",
  "acto sexual",
  "encuentro íntimo",
  "encuentro intimo",
  "desnudez",
  "desnudo",
  "desnuda",
  "cuerpo desnudo",
  "sexualidad humana",
  "relaciones íntimas",
  "relaciones intimas",
  "intimidad física",
  "intimidad fisica",
  "intimidad emocional",
  "sexualidad consentida",
  "relaciones consensuales",
  "consentimiento sexual",
  "consentimiento informado",
  "orientación sexual",
  "identidad de género",
  "identidad de genero",
  "diversidad sexual",
  "homosexualidad",
  "bisexualidad",
  "heterosexualidad",
  "transexualidad",
  "trisexualidad",
  "polisexualidad",
  "pansexualidad",
  "fetichismo",
  "voyeurismo",
  "exhibicionismo",
  "BDSM",
  "sadomasoquismo",
  "fetiche",
  "juguetes sexuales",
  "estimulación erógena",
  "estimulacion erógena",
  "estimulación erogena",
  "estimulacion erogena",
  "pornografía",
  "pornografia",
  "porno",
  "contenido para adultos",
  "material sexualmente explícito",
  "desnudez artística",
  "desnudez artistica",
  "contenido NSFW",
  "NSFW",
  "Not Safe For Work",
  "contenido para mayores de edad",
  "contenido sexualmente sugestivo",
  "escenas de sexo",
  "romance erótico",
  "romance erotico",
  "literatura erótica",
  "literatura erotica",
  "juegos sexuales",
  "prácticas sexuales",
  "practicas sexuales",
  "fantasías sexuales",
  "fantasias sexuales",
  "satisfacción sexual",
  "educación sexual",
  "educacion sexual",
  "salud sexual",
  "consentimiento",
  "límites sexuales",
  "abuso sexual",
  "violencia sexual",
  "agresión sexual",
  "agresion sexual",
  "acoso sexual",
  "explotación sexual",
  "explotacion sexual",
  "tráfico sexual",
  "trafico sexual",
  "puta",
  "zorra",
  "prostituta",
  "perra",
];

export const legal = [
  "ilegal",
  "policia",
  "policía",
  "pasamontañas",
  "pasa montañas",
  "ilicito",
  "ilícito",
  "delito",
  "crimen",
  "infracción",
  "infraccion",
  "ilegalidad",
  "fraude",
  "corrupción",
  "corrupcion",
  "soborno",
  "extorsión",
  "extorsion",
  "malversación",
  "malversacion",
  "lavado de dinero",
  "evasión fiscal",
  "fiscal",
  "evasion",
  "lavado",
  "dinero",
  "defraudación fiscal",
  "defraudacion fiscal",
  "fraude fiscal",
  "blanqueo de capitales",
  "contrabando",
  "blanqueo",
  "tráfico ilegal",
  "trafico",
  "trafico ilegal",
  "piratería",
  "pirateria",
  "robo",
  "hurto",
  "atraco",
  "asalto",
  "estafa",
  "falsificacion",
  "falsificacion",
  "falsedad documental",
  "perjurio",
  "soborno",
  "cohecho",
  "prevaricación",
  "prevaricacion",
  "negligencia",
  "malversación de fondos",
  "malversar",
  "malversacion de fondos",
  "abuso de poder",
  "tráfico de influencias",
  "trafico de influencias",
  "crimen organizado",
  "actividad criminal",
  "pandilla",
  "pandillas",
  "bandas",
  "banda",
  "narco",
  "conspiración",
  "conspiracion",
  "asociación ilícita",
  "ilicita",
  "ílicita",
  "delincuencia",
  "delincuente",
  "delinquir",
  "criminalidad",
  "delincuencia organizada",
  "encubrimiento",
  "complicidad",
  "maleante",
  "encubridor",
  "corrupción política",
  "corrupcion política",
  "corrupcion politica",
  "colusión",
  "colusion",
  "fraude electoral",
  "manipulación del mercado",
  "manipulacion del mercado",
  "insider trading",
  "secuestro",
  "chantaje",
  "trata de personas",
  "trata de blancas",
  "blancas",
  "explotación laboral",
  "explotacion laboral",
  "violación de derechos humanos",
  "violacion de derechos humanos",
  "crímenes de guerra",
  "crimenes de guerra",
  "tráfico de armas",
  "trafico de armas",
  "tráfico de drogas",
  "trafico de drogas",
  "tráfico de personas",
  "trafico de personas",
  "terrorismo",
  "financiamiento del terrorismo",
  "piratería informática",
  "delitos informáticos",
  "delitos informaticos",
  "ciberdelincuencia",
  "violación de la privacidad",
  "violacion de la privacidad",
  "privacidad",
  "violacion",
  "violación",
  "espionaje",
  "acoso",
  "acecho",
  "difamación",
  "difamacion",
  "calumnia",
  "injuria",
  "acosador",
  "acosar",
  "hostigar",
  "hostigamiento",
  "robo de identidad",
  "usurpación de identidad",
  "usurpar",
  "pornografía infantil",
  "explotación infantil",
  "pornografia infantil",
  "explotar",
  "abuso sexual infantil",
  "abusar",
  "evadir",
  "falsificar",
  "poseción",
  "posecion",
  "poseer",
  "atacar",
  "ataque",
  "ataco",
];
